DROP TABLE IF EXISTS users_roles CASCADE;


DROP TABLE IF EXISTS roles CASCADE;


DROP TABLE IF EXISTS phones CASCADE;


DROP TABLE IF EXISTS users CASCADE;

create table phones (phone_id integer generated by default as identity,
 city_code varchar(255),
 country_code varchar(255),
 number varchar(255),
 user_id varchar(255) not null,
 primary key (phone_id));

create table roles (id_role bigint generated by default as identity,
 name varchar(20),
 primary key (id_role));

create table users (id varchar(255) not null,
 created timestamp,
 email varchar(255),
 is_active boolean,
 last_login timestamp,
 modified timestamp,
 name varchar(255),
 password varchar(255),
 token varchar(255),
 username varchar(255),
 primary key (id));

create table users_roles (id_user varchar(255) not null,
 id_role bigint not null,
 primary key (id_user,
 id_role));

alter table users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;

alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);

alter table users drop constraint if exists UK6dotkott2kjsp8vw4d0m25fb7;

alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);

alter table phones add constraint FKmg6d77tgqfen7n1g763nvsqe3 foreign key (user_id) references users;

alter table users_roles add constraint FK3avenccqsoqwrfur1hb8mpbrw foreign key (id_role) references roles;

alter table users_roles add constraint FK6ywr92flw5416dup8uc2egb83 foreign key (id_user) references users;
